### ISSUE TITLE
Create inventory of all pages on website and wiki relating to tool

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/termination-of-transfer#1]
We have the main pages, but need to come up with a complete inventory of the pages that are linked to from the tool that provide additional info about legal concepts and similar in preparation for our legal review and transfer of pages and content to Authors Alliance.

**Comment by peterspdx** [comment]
http://labs.creativecommons.org/demos/termination/

http://labs.creativecommons.org/demos/termination/termination.php

http://labs.creativecommons.org/demos/termination/glossary.html

 http://labs.creativecommons.org/demos/termination/faq.php

**Comment by mattl** [comment]
There are a couple supplementary files too, but we'll package those up.
