### ISSUE TITLE
Privacy Policy Needed

### ISSUE THREAD

**Issue by AAMike** [creativecommons/termination-of-transfer#11]

**Comment by robmyers** [comment]
@peterspdx @AAMike Do we have one we can drop in?

**Comment by peterspdx** [comment]
Not yet. Assigning to myself.

**Comment by robmyers** [comment]
@peterspdx I believe this is now resolved?

**Comment by peterspdx** [comment]
yes can close.

Diane M. Peters
General Counsel, Creative Commons
Portland, Oregon
http://creativecommons.org/staff#dianepeters
13:00-21:00 UTC

**Comment by robmyers** [comment]
And with that we are good to go! :-)
