### ISSUE TITLE
Update ToT tool with new question asking for date first published under grant

### ISSUE THREAD

**Issue by briannaschofield** [creativecommons/termination-of-transfer#116]
Please add a new question (after the current Q3) asking "When was the work first published under the grant?".  If the tool processes termination eligibility under 203, then it should use this date instead of pub_year. (Calculating the date the work was copyrighted for purposes of 304 still should look to the pub_year variable (in addition to other variables).)

**Comment by robmyers** [comment]
@briannaschofield Just to make sure - what is the text of the current Q3?

**Comment by robmyers** [comment]
I am using "This will be used when evaluating termination eligibility in some circumstances." as the explanatory text but it's not very explanatory. :-)

**Comment by robmyers** [comment]
I assume that a publication date before the agreement date, the initial publication date, or the creation date is invalid?

**Comment by briannaschofield** [comment]
Current Q3: When was the work first published?

**Comment by briannaschofield** [comment]
Explanatory text: 

"When a work was first published under the grant (which may be different than the the date the work was published for the first time) can factor into the timing of a termination right. Note that "publication" has a particular meaning in U.S. copyright law, as discussed in our glossary."

("Glossary" should link to the "publication" entry in the glossary.)

**Comment by briannaschofield** [comment]
And yes, the answer to this new question (when a work was first published under the grant) cannot be before the agreement date, the initial publication date, or the creation date (though it could be the same as all three of those dates).
