### ISSUE TITLE
Flag text + "Triggering Publication Date"

### ISSUE THREAD

**Issue by briannaschofield** [creativecommons/termination-of-transfer#118]
The new test for calculating termination under § 203 based on when the work was first published under the grant appears to be working correctly - thank you!  
 
Is it possible to: 
1) add an explanatory flag when that calculation is triggered (i.e. when it is using the date the work was first published under the grant to calculate the windows under § 203), and 
2) to show the a "Triggering Publication Date" line on the output that records the year it was "first published under the grant" (like we did for "effective grant year")?  

I think these two additions will help users understand the results when the first publication date and first publication date under the grant are different.

For the explanatory flag, I think we can say:
Understanding publication dates under § 203 
For terminations under section 203, the Copyright Office calculates the "date of publication" as the date the work is first published _under the grant being terminated_ (which may or may not be the date the work was published for the first time).  When the first publication date under the grant is different than the first publication date, the date of the first publication under the grant is the "triggering publication date" that is used to calculate the notice and termination windows.

**Comment by robmyers** [comment]
1. I have added this.
2. Sorry I'm still working through a cold and my comprehension isn't 100%. We currently show the date as "When was the work first published under the grant?". The "Effective" code on line 148 of questions.js shows two values, the entered year and the one we are using. Is it the case that we should be showing two dates in this instance as well, or is it that we should be showing this date in the PDF as we do for e.g. the window start/ends?

**Comment by briannaschofield** [comment]
I think all we need here is to add a line that shows the "first published under the grant" date on the output (in addition to the first published date, which is already included on the output).  The calculations are correct, but I think it would be useful for the output to also show the date used to calculate the 203 windows.  Does that make any more sense?

**Comment by robmyers** [comment]
Thank you, yes that's great. Added and deployed!

**Comment by robmyers** [comment]
For testing you'll need to flush the cache in your browser - probably control (or command on Mac) - shift - F5.
