### ISSUE TITLE
Tool doesn't accept answer to question #1

### ISSUE THREAD

**Issue by AAMike** [creativecommons/termination-of-transfer#12]
A range of dates entered into "where was the work created" results in no progression (Chrome/Firefox/Safari on Mac OS X)

**Comment by robmyers** [comment]
Which version of OSX please? I've just tried Safari 9.1 and Chrome 51 on El Capitan, and Firefox 44 on Yosemite.

Pressing the "Next" button should move to the next question. Pressing return currently doesn't but support for this is planned. Entering a number doesn't but could be supported.

**Comment by AAMike** [comment]
Whoops—OK, that appears to be it (I was hitting return instead of next).
