### ISSUE TITLE
Questionnaire accepts publication date before creation date

### ISSUE THREAD

**Issue by AAMike** [creativecommons/termination-of-transfer#13]
(decision tree step 1.b.i.)

Should instead for a year on or after creation.

**Comment by robmyers** [comment]
There was no logic in place for this. Adding it revealed a bug in the validation system. That is now fixed.

Thank you for reporting this.

**Comment by robmyers** [comment]
This is now unfixed. Investigating.

**Comment by robmyers** [comment]
Ah just needed to force reload the javascript. It's fine.
