### ISSUE TITLE
Questionnaire gathers information even when it should know that the work is ineligible

### ISSUE THREAD

**Issue by AAMike** [creativecommons/termination-of-transfer#14]
![screen shot 2016-07-03 at 9 49 53 pm](https://cloud.githubusercontent.com/assets/16468568/16551043/33182d1e-4168-11e6-8133-0075a4d4071b.png)

Information gathering (decision tree section 3) is unnecessary where failure is known.

**Comment by robmyers** [comment]
We now jump to the conclusion and do not gather information where failure is known.
