### ISSUE TITLE
The tool is running § 203 analysis (1.f) for pre-78 transfers

### ISSUE THREAD

**Issue by AAMike** [creativecommons/termination-of-transfer#16]
![screen shot 2016-07-03 at 10 10 48 pm](https://cloud.githubusercontent.com/assets/16468568/16551272/200a5c30-416b-11e6-9a27-28eb165092aa.png)

The analysis in 1.f of the decision tree should only apply to transfers from '78 or later (begins with this question about the right of publication).

**Comment by robmyers** [comment]
I put this logic in the section 304 code, as the default for >= 1978 .

This now behaves as specified.
