### ISSUE TITLE
PDF generation failure — HTTP error 500

### ISSUE THREAD

**Issue by AAMike** [creativecommons/termination-of-transfer#17]
For the input pictured here. Google Chrome on Mac OS X El Capitan v 10.11.2.

![screen shot 2016-07-03 at 10 27 18 pm](https://cloud.githubusercontent.com/assets/16468568/16551414/52675d66-416d-11e6-9247-8aff6464bcd2.png)

**Comment by robmyers** [comment]
There was a problem with template and font cache folder permissions on the server.

That is now fixed (and why I didn't see this problem locally, where the code is just being run in my home folder with php -S).

Thank you for reporting this.
