### ISSUE TITLE
Can't say "yes" to question 2.a (Is the agreement or transfer you want to terminate part of a last will and testament?)

### ISSUE THREAD

**Issue by AAMike** [creativecommons/termination-of-transfer#18]
"next"  button is available, but clicking does nothing.
![screen shot 2016-07-12 at 10 51 17 am](https://cloud.githubusercontent.com/assets/16468568/16777508/b1540b00-481e-11e6-8fb9-30c6c51811f5.png)

**Comment by robmyers** [comment]
Can now say yes.

This doesn't short-circuit as it should, though. Investigating.
