### ISSUE TITLE
Debug output page (the final page) after moving through questionnaire

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/termination-of-transfer#2]
At present, it reveals a page a code, not a document with the responses and preliminary determination of termination rights as expected.

**Comment by peterspdx** [comment]
@mattl Anyway that you can debug the output page (last step of the beta tool) by Jan 20th or so?

**Comment by peterspdx** [comment]
Mattl, robmyers: I need to get this last page debugged. It seems a small matter on our side, and it's blocking a large amount of next stage development, none of which can move forward until we have that page fixed. Possible by February 10, please?!?

**Comment by mattl** [comment]
Can you remind me where the tool is?

**Comment by peterspdx** [comment]
http://labs.creativecommons.org/demos/termination/

You can find links to the main pages relative to this tool in the main page describing this github issue. 

The tool is now completely unappealing in look, not sure what happened but it didn't used to look like this, at least when I first filed this issue. Anyway, what is needed is to debug the results page. So, after someone enters information all the way through, there's a page that should show what they need to do next. Currently it's a page with lines of code.

**Comment by mattl** [comment]
Looking, seems like it'll be an easy fix. Gimme a few.

**Comment by mattl** [comment]
@peterspdx take a look now, looks a lot better

**Comment by AAMike** [comment]
Looks are fine on my end, but output is still the page of code.

**Comment by mattl** [comment]
Does the URL change?

**Comment by mattl** [comment]
A screenshot would be very helpful.

**Comment by AAMike** [comment]
Yeah, ends in http://labs.creativecommons.org/demos/termination/create_pdf.cgi

**Comment by AAMike** [comment]
<img width="848" alt="screen shot 2016-02-09 at 4 00 36 pm" src="https://cloud.githubusercontent.com/assets/16468568/12934826/4a21a326-cf46-11e5-9177-257c1e682fae.png">

**Comment by mattl** [comment]
What do you need to enter to get to that form?

**Comment by AAMike** [comment]
Hrm. I was answering all the questions so as to guarantee a positive response—haven't tried doing it another way. Would the full decision tree, as I filled it out, be helpful?

**Comment by mattl** [comment]
Yes it would be :)

I'm filling it out now trying to get an accurate answer.

**Comment by AAMike** [comment]
OK, give me one sec and I'll put that together.

**Comment by AAMike** [comment]
Tell us about the work 

	• Fill out all mandatory fields

Did you, or the author or artist, 
create the work within the 
scope of your, or his or her, employment?

No

Was the work created in response to a special order or commission by some other person or company?

No

Is the agreement or transfer you want to terminate part of a last will and testament?

No

When was the work created?

1979

When was the work first published?

1979

What is the date of the agreement or transfer that you or the author or artist entered into in relation to the work?

1979

Did one or more of the authors or artists enter into the agreement or transfer?

yes

Is [author] currently alive?

yes

**Comment by mattl** [comment]
Okay, thank you.

I'm getting somewhere now. Should have this fixed in a little bit.

**Comment by mattl** [comment]
Okay, PDF output is working. Please confirm and I can close this and go grab a beer ;)

**Comment by AAMike** [comment]
Confirmed! Get a beer!
