### ISSUE TITLE
Incorporate final success blurb into PDF results

### ISSUE THREAD

**Issue by AAMike** [creativecommons/termination-of-transfer#20]
The description issued at the end of the questionnaire should also reappear in the PDF results ("Based on the information provided . . .")

**Comment by robmyers** [comment]
This is now incorporated into the PDF. If we would like to change the formatting within the final success blurb we can format it with html tags (e.g. <br> and <i>) in pub/js/results.json . This will affect the formatting on the HTML page as well.
