### ISSUE TITLE
There should be a "don't know" option for USCO registration _year_ (1.c.i )

### ISSUE THREAD

**Issue by AAMike** [creativecommons/termination-of-transfer#22]
This was only added as a comment to an earlier issue—sorry about that.

**Comment by robmyers** [comment]
There's the option to leave the field blank if the user doesn't know, but that wasn't working. I've fixed it.

I would prefer to not implement anything more complex for this, so if the fixed behaviour isn't ideal I'd prefer to precede this with a radio button choice: "Do you know the registration year? yes/no" that goes to the registration year input if you answer yes and to the next question if you answer no.

**Comment by robmyers** [comment]
Fixed in 427ce3c .
