### ISSUE TITLE
1990 and later works asking about notice

### ISSUE THREAD

**Issue by AAMike** [creativecommons/termination-of-transfer#23]
Only need to ask for 1989 and earlier.

![screen shot 2016-08-15 at 6 50 43 pm](https://cloud.githubusercontent.com/assets/16468568/17685493/4f508b7a-6319-11e6-8280-78d4ebf1a643.png)

**Comment by robmyers** [comment]
We now only ask for works published in 1989 and earlier.

Thank you for reporting this!

**Comment by robmyers** [comment]
Fixed in 427ce3c .
