### ISSUE TITLE
Can't answer "no" to 2.c.i.a — ("was the work created as one of the following…")

### ISSUE THREAD

**Issue by AAMike** [creativecommons/termination-of-transfer#25]
"Next" button is clickable, but clicking does nothing (doesn't advance the tool).

![screen shot 2016-08-24 at 10 49 57 am](https://cloud.githubusercontent.com/assets/16468568/17941586/db2a8bca-69e8-11e6-9198-4591e6be4316.png)

**Comment by robmyers** [comment]
It's answering "don't know" that breaks it, the next question wasn't defined for that.

"don't know" now goes to s2q2d, the same as "no".

Thank you for catching this!

**Comment by robmyers** [comment]
Fixed in 427ce3c .
