### ISSUE TITLE
Information provided in PDF output

### ISSUE THREAD

**Issue by AAMike** [creativecommons/termination-of-transfer#27]
Let's be sure to include at least the:
• notice window (beginning and end)
• termination window (beginning and end)
(these are the most important things)

But I think it would be also good to have (if applicable):
• the publication date
• the registration date
• the creation date

**Comment by robmyers** [comment]
I've renamed the last 3 as "Years", so "Publication Year, Copyright Registration Year, Creation Year".

There's also the "Grant Year" for the year the license (etc.) was granted.

**Comment by robmyers** [comment]
I've added the windows. Let me know if we're missing anything else useful, it's easy enough to add.

Thank you.

**Comment by robmyers** [comment]
Fixed in 427ce3c .
