### ISSUE TITLE
"Conclusion" doesn't reflect result

### ISSUE THREAD

**Issue by AAMike** [creativecommons/termination-of-transfer#29]
The flag looks looks good here, and the windows look good, but it says up top that notification is possible—contradicting the flag that says we're outside the notice window. 

We could just scrap the big bold conclusion, but that text is duplicated on the questionnaire page so it would be best to have it reflect the circumstances if possible.

**Comment by AAMike** [comment]
<img width="772" alt="screen shot 2016-09-21 at 12 49 29 pm" src="https://cloud.githubusercontent.com/assets/16468568/18726639/432ae95a-7ffa-11e6-80d9-4d8d64df94bf.png">

**Comment by robmyers** [comment]
Yes this is because the last question "Did one or more of the authors or artists enter into the agreement or transfer" sets the result. Every answer to it sets a result, and its logic doesn't take into account whether the work is likely public domain, or is outside its notification window.

We need to refactor that logic I think.

**Comment by AAMike** [comment]
Ah. I think the determination in that last question is right—for the question of whether a right will ever be available. We just need to filter it through one more step to determine the relationship between the present time and the windows. 

Need me to throw that logic together?

**Comment by robmyers** [comment]
You have the best handle on the logic so ideally yes. Or if you're pressed for time I can assume that notice window and public domain flags trump this question and implement the logic based on that.

**Comment by AAMike** [comment]
I'll take a stab—should be able to have it in the gdoc later tonight.

**Comment by robmyers** [comment]
Thank you!

**Comment by AAMike** [comment]
OK, here's the easy fix (better documented in gdoc):
1 .change the headline of the result just to say termination eligible
2. place any flags from the A series (that is, flags to do with being outside the window immediately beneath.

I think that be the quickest/easiest and maybe best solution, given we've already done the work to throw up those flags.

**Comment by robmyers** [comment]
I have made these changes in commit a27be06 and deployed them to labs.
