### ISSUE TITLE
Not seeing all flags

### ISSUE THREAD

**Issue by AAMike** [creativecommons/termination-of-transfer#30]
<img width="772" alt="screen shot 2016-09-21 at 12 49 29 pm" src="https://cloud.githubusercontent.com/assets/16468568/18726654/523dc610-7ffa-11e6-8305-5475601d0358.png">

<img width="1153" alt="screen shot 2016-09-21 at 12 53 04 pm" src="https://cloud.githubusercontent.com/assets/16468568/18726697/7d751dc4-7ffa-11e6-9854-26f09ca65632.png">

The inputs above should also trigger flags:
B.1 (triggered at stage 1.a.i.1.b of the decision tree) (no copyright notice)
C.1 (triggered at stage 2.e.i of the decision tree) (possible renegotiations)

(these flags also do not appear when the engine is run solely to trigger them individually)

**Comment by robmyers** [comment]
B.1 is misrepresented as B.i .

C.1 is not added by the code.

I will go through and check all the flags.

**Comment by robmyers** [comment]
Oh hang on, they are i rather than 1. C.i is still not added, investigating the problem with B.i .

**Comment by robmyers** [comment]
The flags are now included in the PDF output (will be deployed later).

How do you mean about running the engine to trigger them?

**Comment by AAMike** [comment]
I meant that I ran the engine so as to only trip _one_ flag at a time, and they still didn't appear. The goal being to make sure that the display issue wasn't a result of having multiple flags.

**Comment by robmyers** [comment]
That makes sense, I just wanted to make sure it wasn't anything more technical.

Thanks.

**Comment by robmyers** [comment]
Fixed in 96b6789 .

Deployed to labs.

Make sure to hard refresh the page before testing, by pressing F5 or Control-Shift-R .
