### ISSUE TITLE
Revised 2.d.i

### ISSUE THREAD

**Issue by AAMike** [creativecommons/termination-of-transfer#31]
Changed a fail to a flag on the basis of legal review (pre-78 creation should no longer fail)

Additionally, added flag to "don't know" answer to post-78.

See proposed decision tree for details.

**Comment by robmyers** [comment]
This is now 2.e.i

**Comment by robmyers** [comment]
Assuming this is 2.e.i, the "don't know" flag was added in commit 96b6789 .

**Comment by robmyers** [comment]
@AAMike please confirm.

**Comment by AAMike** [comment]
No, these are for present 2.d.i.

**Comment by robmyers** [comment]
OK, thanks. :-)

**Comment by robmyers** [comment]
This was added in commit 96b6789 . The section numbers haven't been updated yet so it's still 2.c (s2q2cia) in current git ( commit 53b0659 ).
