### ISSUE TITLE
Revisions to public domain determinations and flags

### ISSUE THREAD

**Issue by AAMike** [creativecommons/termination-of-transfer#32]
In the proposed decision tree. Two changes: 

First: step 1.e (§ 304 analysis) — added test / flag for possible expiration (If $cright_year < 1950 : flag B.iv (Possible expired copyright—possibly public domain);)

Next: copyright term expiration (post-78 works + § 303 works only — i.e., "life of the author" terms) — added test as new 2.b.

**Comment by robmyers** [comment]
1.e < 1950 flag B.iv added.
