### ISSUE TITLE
Can't proceed from 1.f.i for later years

### ISSUE THREAD

**Issue by AAMike** [creativecommons/termination-of-transfer#37]
With 2002 as date input, tool won't go forward from 1.f.i.

![screen shot 2016-09-27 at 10 57 07 am](https://cloud.githubusercontent.com/assets/16468568/18885729/b78c8fa0-84a1-11e6-8360-f1001eeadf15.png)

**Comment by robmyers** [comment]
#41 is the same as this, so merging.

**Comment by robmyers** [comment]
Fixed in ed880af
