### ISSUE TITLE
Secure and register domain(s) for future use when move to neutral name space

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/termination-of-transfer#4]

**Comment by peterspdx** [comment]
CC, CCUS and AuAll to add ideas for domain names to tracking document, to be discuss on Jan 27 check-in call.

@ryanmerkley @mattl if you have thoughts for a neutral namespace domain name please alert me

**Comment by mattl** [comment]
@peterspdx I think you said at ITW that this had happened, so closing it.

**Comment by peterspdx** [comment]
domain names were registered by Authors Alliance, they will hold in their name.
