### ISSUE TITLE
Fix frozen screen and next/back functionality for this search

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/termination-of-transfer#41]
The screen froze with this search:

When was the work created?	1992
Has the work been published?	yes
When was the work first published?	1993
Has the work been registered with the United State Copyright Office?	no
What is the date of the agreement or transfer?
If the agreement predates the work’s creation, please enter the creation year.	1995
Did the agreement or transfer include the right of publication?	yes

After providing a summary of the answers, at this point: “Both notice window and copyright status look good, let’s get some more details!”, both the “back” and “Next” buttons did not seem to function at all.  (Note that the searcher purposefully had the transfer date be after the publication date — just to see what the tool would do with that type of situation).
.

**Comment by AAMike** [comment]
Note, I suspect this issue is actually the same as the one behind issue #37 .

**Comment by robmyers** [comment]
Yes this is the same as #37 . Merging.
