### ISSUE TITLE
Failing after 1.f.i in the 1950s

### ISSUE THREAD

**Issue by AAMike** [creativecommons/termination-of-transfer#44]
James Grimmelmann had two very similar cases resulting in failure at this point:

The first:

> Also loops back to the start. I haven’t been able to get to the details of the work on any set of inputs; it either freezes or restarts no matter what I enter.
> 
> When was the work created?	1950
> Has the work been published?	yes
> When was the work first published?	1950
> Works from 1989 and earlier usually display a copyright notice. Did the work have a copyright notice?	yes
> Has the work been registered with the United State Copyright Office?	yes
> When was the work registered with the United States Copyright Office? (Leave blank if unknown) 1950
> What is the date of the agreement or transfer?
> If the agreement predates the work’s creation, please enter the creation year.

The second:

When was the work created?	1950
Has the work been published?	yes
When was the work first published?	1951
Works from 1989 and earlier usually display a copyright notice. Did the work have a copyright notice?	yes
Has the work been registered with the United State Copyright Office?	yes
When was the work registered with the United States Copyright Office? (Leave blank if unknown) 1951

I'm playing around trying to isolate what's wrong, because similar entries work fine for different years (e.g., clustered around 1928 or 1960)

**Comment by andiwilt** [comment]
Having same issues with years in the 30s and 40s.
For example:
When was the work created? 1940
Has the work been published? yes
When was the work first published? 1943
Works from 1989 and earlier usually display a copyright notice. Did the work have a copyright notice? yes
Has the work been registered with the United State Copyright Office? yes
When was the work registered with the United States Copyright Office? (Leave blank if unknown) 1943
What is the date of the agreement or transfer? 1943
--> Reset

Having same issues with years in the 30s and 40s.
For example:
When was the work created? 1938
Has the work been published? yes
When was the work first published? 1938
Works from 1989 and earlier usually display a copyright notice. Did the work have a copyright notice? yes
Has the work been registered with the United State Copyright Office? yes
When was the work registered with the United States Copyright Office? (Leave blank if unknown) 1939
What is the date of the agreement or transfer: 1939
--> Reset

But
When was the work created? 1940
Has the work been published? yes
When was the work first published? 1960
Works from 1989 and earlier usually display a copyright notice. Did the work have a copyright notice? yes
Has the work been registered with the United State Copyright Office? yes
When was the work registered with the United States Copyright Office? (Leave blank if unknown) 1960
What is the date of the agreement or transfer? 1960
--> Works

**Comment by robmyers** [comment]
@andiwilt Thank you for reporting this.

@AAMike Can you confirm that the algorithm specified in the document covers these cases, and that I have correctly translated the < and > in the document into concrete < > <= >= in the code (I'll be checking as well but you understand the intent better).

**Comment by AAMike** [comment]
I think I've found what might be the issue:

rules.js has been updated with the new public domain flags added in the document (flag B.iv), but results.json does not have flag B.iv added.

Let's see if that isn't the root of the problem. You good to make this change, or do you want me to submit a pull request?

**Comment by robmyers** [comment]
I'll get on it.

Thank you!

**Comment by AAMike** [comment]
There's some more strangeness here-

Current implementation says

`     Values.cright_year = Values.pub_year;
      // If the work is registered (not all works are!), use the min of pub/reg
      if (Values.reg_year != undefined) {
        Values.cright_year = Math.min(Values.pub_year, Values.reg_year);`

Now, there is the possibility that $pub_year is undefined, which could be causing a problem here? 

What we want from this section is to set the copyright year as the lesser of the publication year (if any) or the registration year (if any). If there is neither, an earlier rule would have already terminated the tool as a grant of common law copyright. If only one of those exists, then that's what we want cright_year to be. 

Does that make sense?

**Comment by robmyers** [comment]
I'll check for the case where both are unset as an assert at the start of the function to indicate that it is not a valid state.

The logic for determining the value makes sense.

Thank you.

**Comment by robmyers** [comment]
I've updated the logic but this has led to a new error.   See doc comment.
