### ISSUE TITLE
Flags Are Not Cleared When Back Button Is Pressed

### ISSUE THREAD

**Issue by robmyers** [creativecommons/termination-of-transfer#46]
If the user selects the "Back" button, changes the information they have input, then goes forward they may change the flags that should be applied. But we do not remove flags as we go back. This may lead to incorrect flags in the input.

Change the back button behaviour to strip specified flags, or simply remove the back button if this would be too complex in the available time (if we would have to reference count flags for example).

**Comment by robmyers** [comment]
This is a big enough problem (we need to know which flags to remove and variables to clear at each step back) that I'm going to just remove the back button for now.

**Comment by peterspdx** [comment]
Can we flag those issues that we'll want to consider post v1.0 for the next improved version of the tool? We have a number, including reminder notices, possible registration and similar. Would be nice to track those altogether with a common identifier so we remember to go back to them once we launch. This should be one. Ideas on best way to do that?

**Comment by robmyers** [comment]
We can create a Post v1.0 milestone and add tickets to that? (I just tried that to make sure it works)

**Comment by peterspdx** [comment]
Sounds good to me. @AAMike does this work for you? If so, do you want to go through the issues and identify those that we've agreed would be features added post v1.0?
