### ISSUE TITLE
Prior exercise of termination right not presently asked after

### ISSUE THREAD

**Issue by AAMike** [creativecommons/termination-of-transfer#49]
Particularly relevant for $ 304(d).

**Comment by AAMike** [comment]
Might be best not to implement this, but rather explain in a flag (see issue #50)

**Comment by robmyers** [comment]
Is this superseded by 50, or do we need some new code similar to 50 for it?

**Comment by peterspdx** [comment]
@AAMike Let's discuss today during our 1:1
