### ISSUE TITLE
UX Issues

### ISSUE THREAD

**Issue by AAMike** [creativecommons/termination-of-transfer#6]
- Ability to step backwards after the tool completes is a must (currently, users must start over)
- Do not frontload metadata entry (it's only relevant if tools completes as a positive)
- Frontload date questions — the present approach is duplicative (it asks both regarding work for hire and regarding general eligibility)
- Don't automatically redirect to the PDF on completion—generate a link to it instead.

**Comment by robmyers** [comment]
Tool can now be restarted (and stepped back through).

PDF now loads in separate window.
