### ISSUE TITLE
Generate written summary of termination window test

### ISSUE THREAD

**Issue by AAMike** [creativecommons/termination-of-transfer#64]
As per Molly's comment, quoted below:

> I lied–that was not my final note on the PDF text. Mine does not include publication date, which was relevant to the calculation for my work. Also, I think it would be very valuable (e.g. for the clinic student who helps with this) if the PDF included a 1-2 sentence explanation of the calculation of the termination window. For my work it would be something like “40 years from execution of the agreement, because the agreement covered publication and 40 years from date of agreement is sooner than 35 years from publication, see 17 U.S.C. 203(a)(3).”

**Comment by robmyers** [comment]
Publication date should be included (I just checked with all values as 1968, no registration).

Please provide the values that generated the PDF that did not include the publication year.

**Comment by robmyers** [comment]
The human-readable explanation would be excellent for explaining the conclusion to the legal clinic that the user takes the PDF to but would require its own conclusions.json and another round of development on rules.js.

**Comment by AAMike** [comment]
I similarly was seeing the publication year. I'll ask Molly.

As for the explanation, couldn't we generate it as a flag? That is, if a given test is applied, set a flag with the explanation text as the content? Not the most elegant, but could hack it together w/in a day or two.

**Comment by robmyers** [comment]
The flag approach would work, yes. Is that something you could add and I could merge, or how would that work?

**Comment by AAMike** [comment]
Yes, should be able to. I have another flag project (that regarding the dual window scenarios) that I plan to put together tonight; I should be able to manage to do this one then as well.

**Comment by robmyers** [comment]
Awesome.

**Comment by AAMike** [comment]
This scheme is now in the proposed decision tree

**Comment by AAMike** [comment]
Added flags F.i-iii to results.json / submitted pull request.

**Comment by robmyers** [comment]
Merged.
