### ISSUE TITLE
203 displaying double window with NaN

### ISSUE THREAD

**Issue by AAMike** [creativecommons/termination-of-transfer#75]
<img width="365" alt="screen shot 2016-10-24 at 10 52 42 pm" src="https://cloud.githubusercontent.com/assets/16468568/19674383/afcd59ec-9a3c-11e6-9cf0-6939f8b66a37.png">

What's happening here is that answer to whether the publication right was "maybe"—that's the double window circumstance. That said, the work was never published (so there is no publication date, hence, no window based on the publication date.

**Comment by robmyers** [comment]
If the publication date is undefined, adding 25 to it gives NaN in JavaScript. Fixing.

**Comment by robmyers** [comment]
Is it the case that we wouldn't have a window in the first slots as seen above (2003-2016, 2013-2018) under some circumstances?

**Comment by robmyers** [comment]
Implementing logic to handle that as well.
