### ISSUE TITLE
Public domain test

### ISSUE THREAD

**Issue by AAMike** [creativecommons/termination-of-transfer#91]
We presently end the tool where publication date is before 1923, but don't do the same where _registration_ is before 1923. Should be a quick fix.

**Comment by AAMike** [comment]
Note: until this is fixed, the new 304(d) test can be broken by unpublished, registered pre-23 works.

**Comment by robmyers** [comment]
This would be in Rules.s1q1ci .

**Comment by robmyers** [comment]
What should the conclusion be? e.g. B.viii

**Comment by robmyers** [comment]
Assuming B.viii.

Fixed in 345d618d8f31a3f431a95dbfb6ccd2b056653b68 .

**Comment by AAMike** [comment]
Yes, confirmed: B.viii.

**Comment by robmyers** [comment]
Thank you.
