### ISSUE TITLE
203 & 304 eligible grants

### ISSUE THREAD

**Issue by AAMike** [creativecommons/termination-of-transfer#95]
Presently, the system considers EITHER 203 or 304, however, a work created before 78 (thus 304 eligible) might be transferred post 78 (thus 203 eligible). In an ideal world, we would have two full sets of results in such circumstances.

We can either:

1. Implement in V.2, and in the meantime throw a flag in all relevant 203 results saying that 304 might be possible
3. Sprint and get it done this weekend?

**Comment by robmyers** [comment]
We will need to:

* Change the logic to detect this condition, and change the flow of the questions to follow both paths if appropriate.
* Separate out Values.notice_begin/end and Values.term_begin/end for 203 and 304, and change the PDF rendering logic to use the new values.
* Allow more than one conclusion to be stored in Values.conclusion, change the logic in Rules.conclusion to not automatically jump to the finish, change other logic to check for multiple values, and change the PDF rendering logic to display multiple conclusions.

I don't think any of these are particularly complex as long as we don't miss any shared variables.

**Comment by AAMike** [comment]
OK, here's what I think, in pseudocode, what the triggering logic looks like for the two analyses:

`if ((pub_year || reg_year) < 1978 {
	304_analysis();
}

if (k_Year > 1977) {
	203_analysis();
}
