### ISSUE TITLE
Can't answer "no" to s2q2f

### ISSUE THREAD

**Issue by AAMike** [creativecommons/termination-of-transfer#98]

**Comment by robmyers** [comment]
In rules.js we have Rules.s2q2f and Rules.s2q2fii, with Rules.s2q2f going to Rules.s2q2fii if we do not choose "yes" for it.

In questions.js we have Questions.s2q2f and Questions.s2q2eii. The latter uses the same variable name (agreement_by_family_or_executor) as Rules.s2q2fii, so it does look like Questions.s2q2eii should be Questions.s2q2fii.

To make the smallest number of changes required to fix this, I'm going to change the e to an f in just one location to make Questions.s2q2fii .
